### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by xsuchy09** [Kdyby/Redis#89]
Why PHP 7.4 is not supported? Can I help in some way?

**Comment by VBoss** [comment]
PHP 7.4 isn't supported because nette/tester(maybe other packages too) in required version could not run with newer PHP. 

If you want help, look here https://github.com/Kdyby/Redis/pull/86#issuecomment-571471729 there was discussion about this topic. Best solution is probably as commented split PR and continue that way.

**Comment by VBoss** [comment]
Aaaand done. Release - https://github.com/Kdyby/Redis/releases/tag/v5.1.0
